baseURL = "https://zjunior06.tech"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Zilberto Junior | Home"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "itsjoeoui"

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "zjunior06"
author = "Zilberto Junior"
copyright = "2020-2021"
description = "Welcome to my website :P"
profilePicture = "https://avatars0.githubusercontent.com/u/25695219?v=4"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/zjunior06"

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "Telegram"
url = "https://t.me/zjunior06"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:zjunior06@pixelexperience.org"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "PixelExperience"
  weight = 300
  identifier = "pixelexperience"
  url = "https://download.pixelexperience.org/team/zjunior06"
 
  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
