baseURL = "https://zjunior06.tech"
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Zilberto Junior | Home"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "itsjoeoui"

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Zilberto Junior"
author = "Zilberto Junior"
copyright = "2020-2021"
description = "Welcome to my website :P"
profilePicture = "https://avatars3.githubusercontent.com/u/48398637?s=460&u=ddf4aec72b79d50a9f37ca1dc5b7444c1940f966&v=4"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

[languages]
  [languages.en]
    title = "Zilberto Junior | home"
    languageName = "English"
    weight = 1
  [languages.ptbr]
    title = "Zilberto Junior | inicio"
    languageName = "Portugues"
    weight = 2

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/zjunior06"

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "Telegram"
url = "https://t.me/zjunior06"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:zjunior06@pixelexperience.org"

## Menu items

[menu]

  [[Languages.ptbr.menu.main]]
  url = "/ptbr/"
  identifier = "home"
  name   = "Inicio"
  weight = 100

  [[Languages.ptbr.menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/ptbr/post/"

  [[Languages.ptbr.menu.main]]
  name = "PixelExperience"
  weight = 300
  identifier = "pixelexperience"
  url = "https://download.pixelexperience.org/team/zjunior06"
  
  [[Languages.ptbr.menu.main]]
  name = "Sobre"
  weight = 400
  identifier = "about"
  url = "/ptbr/about/"

  [[Languages.en.menu.main]]
  url = "/en/"
  identifier = "home"
  name   = "Home"
  weight = 100

  [[Languages.en.menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/en/post/"

  [[Languages.en.menu.main]]
  name = "PixelExperience"
  weight = 300
  identifier = "pixelexperience"
  url = "https://download.pixelexperience.org/team/zjunior06"
  
  [[Languages.en.menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/en/about/"
